apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-ai-data
  namespace: echo-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-redis-data
  namespace: echo-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
