import DOMPurify from "dompurify";
import { useEffect, useMemo, useRef, useState } from "react";

import type { AIMessage, Message } from "@/core/api/types";
import { jsonAuthHeaders } from "@/core/auth/api";
import { getBackendBaseURL } from "@/core/config";
import { dispatchQuickReply } from "@/core/messages/quick-reply";
import { findToolCallResult } from "@/core/messages/utils";

type VisualReceipt = {
  kind: "echo.visual.v1";
  visual_id: string;
  receipt_token: string;
  thread_id: string;
};

export function parseVisualReceipt(result: unknown): VisualReceipt | null {
  let value = result;
  if (typeof value === "string") {
    try {
      value = JSON.parse(value.slice(value.indexOf("{")));
    } catch {
      return null;
    }
  }
  if (!value || typeof value !== "object") return null;
  const row = value as Record<string, unknown>;
  if (row.kind !== "echo.visual.v1" || row.ok !== true) return null;
  if (
    ![row.visual_id, row.receipt_token, row.thread_id].every(
      (v) => typeof v === "string",
    )
  )
    return null;
  return row as unknown as VisualReceipt;
}

// Both partial and final frames have an opaque origin. Only completed HTML may
// run inline scripts; network resources and access to the host are unavailable.
export function buildVisualDocument(
  code: string,
  format: string,
  channel: string,
  complete: boolean,
): string {
  // Template contents stay inert, including resource loads, in the host page.
  const template = document.createElement("template");
  template.innerHTML = code;
  const fragment = template.content;
  let blockedResources = !!fragment.querySelector(
    "script[src],iframe,object,embed,link",
  );
  const scripts =
    complete && format === "html"
      ? Array.from(fragment.querySelectorAll("script:not([src])")).map(
          (script) => script.textContent ?? "",
        )
      : [];
  fragment
    .querySelectorAll("script,meta,base,iframe,object,embed,link")
    .forEach((node) => node.remove());
  fragment.querySelectorAll("[src]").forEach((node) => {
    if (!/^(data:|blob:)/i.test(node.getAttribute("src") || "")) {
      blockedResources = true;
      node.removeAttribute("src");
    }
  });
  const source = template.innerHTML;
  const clean = DOMPurify.sanitize(source, {
    USE_PROFILES:
      format === "svg"
        ? { svg: true, svgFilters: true }
        : { html: true, svg: true, svgFilters: true },
    ADD_TAGS: ["style"],
    FORBID_TAGS: [
      "script",
      "iframe",
      "object",
      "embed",
      "base",
      "meta",
      "link",
      "form",
    ],
    FORBID_ATTR: [
      "href",
      "xlink:href",
      "target",
      "action",
      "formaction",
      "srcset",
    ],
  });
  // Channel is generated by the host, never interpolated from model output.
  const nonce = channel.replace(/[^a-zA-Z0-9-]/g, "");
  const bridge = `(() => {
    const send = (type, detail = '') => parent.postMessage({channel: ${JSON.stringify(channel)}, type, detail}, '*');
    let failed = false;
    const fail = detail => { failed = true; send('error', String(detail).slice(0, 1000)); };
    addEventListener('error', e => fail(e.message || 'Resource failed'), true);
    addEventListener('unhandledrejection', e => fail(e.reason?.message || e.reason || 'Unhandled rejection'));
    addEventListener('securitypolicyviolation', e => fail('Blocked resource: ' + e.violatedDirective));
    addEventListener('DOMContentLoaded', () => {
      if (${complete && blockedResources}) fail('External resources or embedded pages are unsupported; use self-contained HTML/SVG.');
      const calculateHeight = () => {
        const body = document.body;
        const html = document.documentElement;
        if (!body) return 160;
        return Math.ceil(Math.max(body.scrollHeight, html ? html.scrollHeight : 0, body.offsetHeight));
      };
      const resize = () => send('resize', calculateHeight());
      if (typeof ResizeObserver !== 'undefined' && document.body) {
        const observer = new ResizeObserver(resize);
        observer.observe(document.body);
        if (document.documentElement) observer.observe(document.documentElement);
      }
      resize();
      requestAnimationFrame(() => requestAnimationFrame(() => { if (!failed) send('rendered'); }));
    });
  })();`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; img-src data: blob:; font-src 'none'; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none';"><meta name="viewport" content="width=device-width,initial-scale=1"><style>html{color-scheme:light dark}body{margin:0;padding:16px;font:14px system-ui;box-sizing:border-box;overflow-wrap:anywhere}svg{max-width:100%;height:auto}button,input,select{font:inherit}*{box-sizing:border-box}</style><script nonce="${nonce}">${bridge}</script></head><body>${clean}${scripts.map((script) => `<script nonce="${nonce}">${script}</script>`).join("")}</body></html>`;
}

export function InlineVisual({
  title,
  code,
  format,
  receipt,
  complete,
}: {
  title: string;
  code: string;
  format: string;
  receipt: VisualReceipt | null;
  complete: boolean;
}) {
  const frame = useRef<HTMLIFrameElement>(null);
  // A fresh channel per render input, so a reply from the previous iframe
  // document can never be mistaken for the current one.
  // eslint-disable-next-line react-hooks/exhaustive-deps -- deps are the trigger, not inputs
  const channel = useMemo(() => crypto.randomUUID(), [code, complete]);
  const [height, setHeight] = useState(360);
  const [status, setStatus] = useState("等待浏览器渲染");
  const [detail, setDetail] = useState("");
  const [showSource, setShowSource] = useState(false);
  const [action, setAction] = useState("");
  const srcDoc = useMemo(
    () => buildVisualDocument(code, format, channel, complete),
    [code, format, channel, complete],
  );
  const visualId = receipt?.visual_id;
  const token = receipt?.receipt_token;

  useEffect(() => {
    setStatus(complete ? "等待浏览器渲染" : "生成中 · 静态预览");
    setDetail("");
    let failed = false;
    let rendered = false;
    let active = true;
    const controller = new AbortController();
    const listener = (event: MessageEvent) => {
      if (
        event.source !== frame.current?.contentWindow ||
        event.data?.channel !== channel
      )
        return;
      const { type, detail: message } = event.data as {
        type: string;
        detail: unknown;
      };
      if (type === "resize") {
        if (typeof message === "number" && Number.isFinite(message))
          setHeight(Math.min(1200, Math.max(160, message)));
        return;
      }
      if (!complete || !["rendered", "error"].includes(type) || failed) return;
      if (type === "rendered" && rendered) return;
      rendered = true;
      failed = type === "error";
      setStatus(failed ? "渲染出错" : "浏览器已渲染");
      const error = failed
        ? String(message ?? "Render failed").slice(0, 1000)
        : "";
      setDetail(error);
      if (!visualId || !token) return;
      void fetch(
        `${getBackendBaseURL()}/api/visuals/${encodeURIComponent(visualId)}/receipt`,
        {
          method: "POST",
          headers: jsonAuthHeaders(),
          signal: controller.signal,
          body: JSON.stringify({
            receipt_token: token,
            status: type,
            detail: error,
          }),
        },
      )
        .then((response) => {
          if (!response.ok) throw new Error("Receipt unavailable");
        })
        .catch(() => {
          if (active)
            setDetail(
              (previous) =>
                previous || "本地显示状态未同步；Agent 尚未收到回执。",
            );
        });
    };
    window.addEventListener("message", listener);
    const timer = window.setTimeout(() => {
      if (active)
        setStatus((previous) =>
          previous === "等待浏览器渲染" ? "尚未收到浏览器回执" : previous,
        );
    }, 10000);
    return () => {
      active = false;
      controller.abort();
      clearTimeout(timer);
      window.removeEventListener("message", listener);
    };
  }, [channel, complete, visualId, token]);

  const request = (save: boolean) => {
    if (!receipt?.thread_id) return;
    const text = save
      ? `请把可视化 ${receipt.visual_id}（${title}）保存为当前任务工作区的 ${format === "svg" ? "SVG 和 HTML" : "HTML"} 产物，沿用产物预览和版本管理，并给出文件链接。`
      : `请修复可视化 ${receipt.visual_id}（${title}）。浏览器报错：${detail || status}。修正后重新 show_visual。`;
    setAction(
      dispatchQuickReply({ threadId: receipt.thread_id, text })
        ? "已提交到当前任务"
        : "当前任务输入不可用，请复制源码保存。",
    );
  };

  return (
    <section
      className="not-prose my-3 overflow-hidden rounded-lg border"
      aria-label={title}
      data-testid="inline-visual"
    >
      <header className="flex flex-wrap items-center gap-2 border-b bg-muted/30 px-3 py-2 text-xs">
        <strong className="mr-auto font-medium text-foreground">{title}</strong>
        <span role="status" className="text-muted-foreground">{status}</span>
        <button
          type="button"
          className="rounded px-2 py-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
          onClick={() => setShowSource((value) => !value)}
        >
          {showSource ? "查看图形" : "查看源码"}
        </button>
        {receipt?.thread_id && (
          <button
            type="button"
            className="rounded px-2 py-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
            onClick={() => request(true)}
          >
            保存为产物
          </button>
        )}
        {status === "渲染出错" && receipt?.thread_id && (
          <button
            type="button"
            className="rounded px-2 py-0.5 text-destructive transition-colors hover:bg-destructive/10"
            onClick={() => request(false)}
          >
            请求修复
          </button>
        )}
      </header>
      {detail && (
        <p className="px-3 py-1.5 text-xs text-destructive" role="alert">
          {detail}
        </p>
      )}
      {action && (
        <p className="px-3 py-1 text-xs text-muted-foreground" role="status">
          {action}
        </p>
      )}
      <iframe
        ref={frame}
        title={title}
        sandbox="allow-scripts"
        referrerPolicy="no-referrer"
        srcDoc={srcDoc}
        className={showSource ? "hidden" : "w-full border-0 transition-[height] duration-200 ease-out"}
        style={{ height }}
      />
      {showSource && (
        <pre className="max-h-96 overflow-auto p-3 text-xs">
          <code>{code}</code>
        </pre>
      )}
    </section>
  );
}

export function InlineVisualMessages({ messages }: { messages: Message[] }) {
  const visuals: React.ReactNode[] = [];
  const seen = new Set<string>();
  for (const message of messages) {
    if (message.type !== "ai") continue;
    for (const call of (message as AIMessage).tool_calls ?? []) {
      if (call.name !== "show_visual" || !call.id || seen.has(call.id))
        continue;
      seen.add(call.id);
      const { title, code, format = "svg" } = call.args ?? {};
      if (
        typeof code !== "string" ||
        !code.trim() ||
        code.length > 100000 ||
        !["html", "svg"].includes(String(format))
      )
        continue;
      const result = findToolCallResult(call.id, messages);
      const receipt = parseVisualReceipt(result);
      // A rejected tool call must never execute the rejected HTML.
      if (result && !receipt) continue;
      visuals.push(
        <InlineVisual
          key={call.id}
          title={typeof title === "string" ? title.slice(0, 160) : "可视化"}
          code={code}
          format={String(format)}
          receipt={receipt}
          complete={!!receipt}
        />,
      );
    }
  }
  return <>{visuals}</>;
}
